### ISSUE TITLE
Data load issue

### ISSUE THREAD

**Issue by lucifer-dev-cyber** [algotom/algotom#11]
Here is the problem faced by me.

[Algotom_Data_Load_issue.pdf](https://github.com/algotom/algotom/files/10854362/Algotom_Data_Load_issue.pdf)

I have algotom module installed but still facing this module issue.

**Comment by nghia-vo** [comment]
The function you're using belong to different module: https://algotom.readthedocs.io/en/latest/toc/api/algotom.io.converter.html, not loadersaver. Need to import it first:
```python
import algotom.io.converter as conv
# Then use it as
conv.convert_tif_to_hdf()...
It's better using a IDE (Pycharm, VSCode) which can help with autocompletion: https://algotom.readthedocs.io/en/latest/toc/section1/section1_1.html#fig-1-1-3
to avoid this mistake.

**Comment by lucifer-dev-cyber** [comment]
Thanks.

There was same error mentioned in website here- https://algotom.readthedocs.io/en/latest/toc/section1/section1_2.html#tiff-form. Just wanted to highlight it.

![Screenshot_54](https://user-images.githubusercontent.com/119943034/222104436-e5230906-01e7-4a6f-9aa6-1a1bacb873e2.jpg)
at.

**Comment by nghia-vo** [comment]
Ha, thanks for that. I edited that document in rst text format so didn't catch the mistake. I've updated the document, you may need to refresh browser to see the change.
