### ISSUE TITLE
Half aquisition reconstruction issue

### ISSUE THREAD

**Issue by maria-demilo** [algotom/algotom#12]
I refered to this- https://algotom.readthedocs.io/en/latest/toc/section1/section1_4.html. Used example 1.4.8.2. Sinogram stitching for a half-acquisition scan, and tried to performing my reconstruction. Here in my case sample is twice larger than beem, but during the 360 degree scan it fits the beam.

Not able to reconstruct it. Here is my jupyter notebook- 
[half_acq.pdf](https://github.com/algotom/algotom/files/10879739/half_acq.pdf)

**Comment by nghia-vo** [comment]
Interesting! The converted sinogram looks ok. In your notebook, correct this line:
```python
img_rec = reco.fbp_reconstruction(sino_ext, center2, angles=angles, apply_log=False, gpu=True)
````
because you already converted angles to radian above (In[3])
Could you save the sino_360 to tiff and upload to google drive or e-mail me (nvo@bnl.gov)?
Out of that, you can try with manual searching:
```python
#Change step for coarse and fine search
output = "E:/tmp/"
for center0 in np.arange(5, 150, 5):
       sino_180, center1 = conv.convert_sinogram_360_to_180(sino_360, center0)
       name = "0000" + str(center0)
       file_name = output + "/center_" + name[-5:] + ".tif"
       rec_img = reco.dfi_reconstruction(sino_180, center1, apply_log=True)
       losa.save_image(output, rec_img)
```

**Comment by maria-demilo** [comment]
Tried the following mentioned above. Did'nt get the reconstruction.

I have sent you a mail with drive link.

**Comment by nghia-vo** [comment]
The data was acquired incorrectly as the rotation axis is out of the field of view. I tried to find the center by visual inspection, there's no position giving good result. Unfortunately, you have to collect data again. Making sure that the rotation axis is at the size of the field of view: https://opg.optica.org/getimagev2.cfm?img=ttc%2B%2Bo3FJqYTj5xD7MIL3DnpY3OhxvRPeiWuqKbKSnA%3D

```python
import numpy as np
import algotom.io.loadersaver as losa
import algotom.prep.correction as corr
import algotom.prep.calculation as calc
import algotom.prep.conversion as conv
import algotom.rec.reconstruction as reco
import algotom.prep.filtering as filt
import matplotlib.pyplot as plt

proj = np.load("E:/Tomo_data/proj.npy")
flat = np.mean(np.load("E:/Tomo_data/flat.npy"), axis=0)
dark = np.mean(np.load("E:/Tomo_data/dark.npy"), axis=0)

output_base0 = "E:/tmp/test_find_center/"
output_name = losa.make_folder_name(output_base0, name_prefix="Find_center")
output_base = output_base0 + "/" + output_name

(depth, height, width) = proj.shape
idx = height // 2

sino_360 = corr.flat_field_correction(proj[:,idx,:], flat[idx], dark[idx])
losa.save_image(output_base0 + "/sino_360.tif", sino_360)

db_width = 2 * width
for center0 in range(0, width, 20):
    sino_180, center1 = conv.convert_sinogram_360_to_180(sino_360, center0)
    rec_img = reco.gridrec_reconstruction(sino_180, center1, apply_log=True,
                                          ratio=None)
    size = rec_img.shape[0]
    pad = db_width - size
    pad1 = pad // 2
    pad2 = pad - pad1
    rec_pad = np.pad(rec_img, ((pad1, pad2), (pad1, pad2)), mode="edge")
    file_name = "rec_img_" + ("0000" + str(center0))[-5:] + ".tif"
    losa.save_image(output_base + "/" + file_name, rec_pad)
```

**Comment by maria-demilo** [comment]
I would like to mention here that the sample width is 6.3mm and the beem width is 3.2mm. We have made sure that the centre of rotation is along the edge so as fit the sample in a 360 degree scan. when we look at the data and plot sinogram the centre is along the edge. And when we stich the sinogram together, probably the center will be around the centre of the sinogram.

What do you think? this information should help?

**Comment by maria-demilo** [comment]
We have also done a same scan of 720 degree whould that help in any ways?

**Comment by maria-demilo** [comment]
I apologise for sharing the half data. I have updated the numpy array in the drive. I realised that I have shared 3600 projection data, but I have 7200 projection data with step size of 0.05 degree.

I have also sent you email again.

**Comment by maria-demilo** [comment]
Previously atlest I got a good sinogram, but now after uploading full data.. stiched sinogram seems strange.

**Comment by nghia-vo** [comment]
A common mistake of trying the double field-of-view technique is that users move the sample instead of the rotation axis as shown below. 
![demo_FOV](https://user-images.githubusercontent.com/12136997/224136044-60aa3ebe-9ca3-419a-989d-6c3aa0ab8191.jpg)

You also can check by compare the projection image at 0 degree and 180-degree to see if there's any overlap area.

```python
import numpy as np
import algotom.io.loadersaver as losa
import algotom.prep.correction as corr

proj = np.load("E:/Tomo_data/proj.npy")
flat = np.mean(np.load("E:/Tomo_data/flat.npy"), axis=0)
dark = np.mean(np.load("E:/Tomo_data/dark.npy"), axis=0)

output_base0 = "E:/tmp/test_find_center/"
output_name = losa.make_folder_name(output_base0, name_prefix="Find_center")
output_base = output_base0 + "/" + output_name

(depth, height, width) = proj.shape
idx = height // 2

proj_first = corr.flat_field_correction(proj[0], flat, dark)
losa.save_image(output_base0 + "/proj_first.tif", proj_first)
proj_first = corr.flat_field_correction(proj[depth//2], flat, dark)
losa.save_image(output_base0 + "/proj_mid.tif", proj_first)
proj_last = corr.flat_field_correction(proj[-1], flat, dark)
losa.save_image(output_base0 + "/proj_last.tif", proj_last)
```
Unfortunately, if the data was acquired incorrectly, there's nothing can do about it.
