### ISSUE TITLE
Issue about remove_stripe_based_fitting

### ISSUE THREAD

**Issue by Eugene-JPI** [algotom/algotom#14]
Hi
I've tried stripe_based _fitting but the image changes.
Below is the code I modified for extra stripes.

def remove_all_stripe(sinogram, snr=3.0, la_size=51, sm_size=21,
                      drop_ratio=0.1, dim=1, **options):

    sinogram = remove_dead_stripe(sinogram, snr, la_size, residual=False)
    sinogram = remove_large_stripe(sinogram, snr, la_size, drop_ratio,
                                   **options)
    sinogram = remove_stripe_based_sorting(sinogram, sm_size, dim, **options)
    sinogram = remove_stripe_based_fitting(sinogram, order=1, sigma=10,
                                          num_chunk=9, sort=True, **options)
    return sinogram
    
  I just added the 
      sinogram = remove_stripe_based_fitting(sinogram, order=1, sigma=10,
                                        num_chunk=9, sort=True, **options)
   at last but the image is bit different before adding the remove_stripe_based_fitting function.
     
And this is how I called the function
    corrected_sino_chunk = Parallel(n_jobs=ncore)(
        delayed(rem.remove_all_stripe)(sino, snr=3.0, la_size=81, sm_size=31) for sino in scaled_sino_chunk
    )

![image](https://github.com/user-attachments/assets/c4765dd2-f2ab-4c61-a088-80e745cb99ba)
![image](https://github.com/user-attachments/assets/3f7e3463-c563-4fe0-8b06-76f90654d6ad)

Left is the one with fitting function and the right is the result without fitting function.

Also, the image brightness around center became darker at some slices after applying fitting while the right one is 
relatively uniform.

![image](https://github.com/user-attachments/assets/69edd3cf-a7d7-4df7-b052-3bea017deb3a)

Could you suggest any potential cause of this problem so that I could give a try to fix?

I’m also curious why Algorithm 1, in particular, performs better in handling low-contrast ring artifacts although Algorithms 1, 2, and 3 seem to work on similar principles,

Thanks

**Comment by Eugene-JPI** [comment]
Thanks for the reply.
I have tried with various parameters and also gave change to the combination of methods in algotom such as replacing fitting function with remove_large_stripe function or changing the orders of remove_all_stripe.
But it seems that low-contrast rings are hard to remove for my datasets which has abrupt changes in intensity without making any additional artifacts. (The degree of the low-contrast ring is similar to the one on the third from the right in the text above. It is not clearly visible)
Based on your papers and my experiments so for, I guess that to erase low-contrast ring, the only way is to use remove_stripe_based_fitting.
Is it right? or is there any thing that I could give a try?

**Comment by nghia-vo** [comment]
Indeed, low-contrast rings are difficult to remove without changing the features of the image.

For your datasets, the key question is whether the low-contrast rings will interfere with image segmentation. If they don’t, then no further action is needed.

To remove low-contrast rings, you could try other options like FFT-based or wavelet-FFT-based methods. However, they always produce side-effect artifacts.

**Comment by nghia-vo** [comment]
I will close this issue for now. The next feature for Algotom will be low-pass ring artifact removal.

**Comment by Eugene-JPI** [comment]
Thanks, I'm really looking forward to it.
