### ISSUE TITLE
Unexpected sub-pixel shift behaviour in scipy.ndimage.shift

### ISSUE THREAD

**Issue by ajulik1997** [algotom/algotom#17]
Currently, `scipy.ndimage.shift` is used for sub-pixel image alignment. However, I have noticed several interesting behaviours that may not do what is intended. Line ref: https://github.com/algotom/algotom/blob/18ad6d7e23d01d115c1b15847db25981003dae1d/algotom/prep/phase.py#L679C38-L679C39

Firstly, if you don't specify the spline interpolation order, it defaults to 3, therefore carrying out a pre-filtering operation. This temporarily allocates a `float64` array which may cause OOM exceptions (particularly for large stitched sinograms). I would have suggested to default to order 1 (computationally cheaper, avoids prefiltering operation, avoids silently allocating lots of memory), however, I have noticed other interesting behaviour (rounding is used only to make the output easier to compare):

```
>>> a = np.zeros((5, 5), dtype=np.float32)
>>> a[:2, :2] = 1
>>> a
array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)
>>> ndimage.shift(a, [0.25, 0.25], order=1).round(2)
array([[0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.25, 0.  , 0.  ],
       [0.  , 0.25, 0.06, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  ]], dtype=float32)
```

I would have expected some non-zero values in the first row and column. This is the case for even very small shifts (0.01), and for any interpolation order, eg your default:

```
>>> ndimage.shift(a, [0.25, 0.25]).round(2)
array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  1.17,  0.24, -0.06,  0.01],
       [ 0.  ,  0.24,  0.05, -0.01,  0.  ],
       [ 0.  , -0.06, -0.01,  0.  , -0.  ],
       [ 0.  ,  0.01,  0.  , -0.  ,  0.  ]], dtype=float32)
```

Are you aware of this behaviour? Do you think the initial empty rows and cols have any effect on speckle shifts (or grid reconstruction stitching, which is what I am attempting to implement)?

**Comment by nghia-vo** [comment]
This is normal when you test on simulated data where there's sharp jump of intensity between points (step function). Another the way to see the behaviour is to apply a polynomial fit on a step function. Scipy.ndimage.shift uses spline interpolation, a polynomial type, so it's expected behaviour when you use interpolation with oder >1 on a step function.

For real data, which impacts by a point spread function and noise, using order > 1 is more robust. I did compare between interpolation methods (linear vs cubic) for image shifting here: figure 10 of [this paper](https://doi.org/10.1364/OE.22.019078).

Using different orders of scipy.shift has been tested in different algotom modules: calculation.py, correlation.py. Oder of 3 is good for most of the cases, so you're good to go.

**Comment by ajulik1997** [comment]
Thanks for your reply, yes my initial memory issues were related to me trying to work on a whole 3D array, moving it to 2D or chunked 3D has solved that. Although I'm still not sure about the efficiency of making repetitive `float64` allocations, it's significantly more feasible for 2D slices.

As for order 3 interpolation, yes I was initially quite sceptical but looking at the figure you linked, I see it has its benefits in many scenarios. From my understanding though, even with pre-filtering, I don't think `ndimage.shift` operates correctly for less-than-one pixel shifts, where I see it uses the padding of choice (constant), but I would have expected something in the first row and col. Here is the output for order 3, with prefiltering, and "smooth" data:

```
>>> a
array([[1. , 0.8, 0.6, 0.4, 0.2],
       [0.8, 0.6, 0.4, 0.2, 0. ],
       [0.6, 0.4, 0.2, 0. , 0. ],
       [0.4, 0.2, 0. , 0. , 0. ],
       [0.2, 0. , 0. , 0. , 0. ]])
>>> ndimage.shift(a, (0.25, 0.25), order=3).round(2)
array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.74,  0.51,  0.33,  0.08],
       [ 0.  ,  0.51,  0.3 ,  0.07, -0.01],
       [ 0.  ,  0.33,  0.07, -0.01,  0.  ],
       [ 0.  ,  0.08, -0.01,  0.  , -0.  ]])
```

Regardless, this no longer seems like an algotom-relevant issue, so I'm closing the issue.

**Comment by nghia-vo** [comment]
Yes, you're right about padding zeros using pre-filtering with sub-pixel. I think scipy.ndimage.shift may use numpy.pad behind which explains this output (pad value in numpy.pad is integer). Anyway, algotom uses "reflect" or "edge" as default padding methods, so we are good.
