### ISSUE TITLE
Documentation: Clarify that overlap_position is w.r.t the center of search window

### ISSUE THREAD

**Issue by ajulik1997** [algotom/algotom#18]
Minor suggestions, but it would make sense to clarify to the users reading the documentation that the `overlap_position` parameter from various `find_overlap` functions is actually with respect to the **middle** of the search window. The wrong assumption I made based on reading the documentation is that `find_overlap` is defined irrespective of the window, such that over overlap start is at `overlap_position`, and the total length of the array in the overlap search direction is `overlap_position+overlap`. However, only after inspecting the code did I deduce that in fact the start of the overlap is `overlap_position - (window_size / 2)`, and the total length of the array is therefore `overlap_position - (window_size / 2) + overlap`.

https://github.com/algotom/algotom/blob/6a068a5e948ec90e8a3f4ffc203b91f0967ec50c/algotom/prep/calculation.py#L543

**Comment by nghia-vo** [comment]
Good suggestion Alex, I'll update that.

**Comment by nghia-vo** [comment]
Documentation been updated both on readthedocs and github.io
