### ISSUE TITLE
The contradiction of the center of rotaion calculated by tomopy and algotom

### ISSUE THREAD

**Issue by gbzan** [algotom/algotom#7]
The algotom is so useful for my project. Thanks for you great contribution. I used "find_center_vo" method to try to get the center of rotation of a sinogram.  One function is from tomopy, the other one is algotom.  The "find_center_vo" of tomopy  gave me the right number. The "find_center_vo" of algotom seems to  give me the wrong number. I plotted the Fourier metric for coarse_search_cor and fine_search_cor, it seems it didn't give me the minimum Fourier metric. Could you please check what't the different between the "find_center_vo" in tomopy and algotom? And could you please tell me how to fix the problem in algotom? Thank you.

![image](https://user-images.githubusercontent.com/32512895/166501205-a56d61b5-7e9f-49d2-8ed6-36c3532d965b.png)

**Comment by nghia-vo** [comment]
@gbzan: Thanks for using Algotom and the feedback. The metric indicates that the center is out of the search range. We need to extend the range more to the right side. 

In algotom, if users don't provide the search range, the [function](https://github.com/algotom/algotom/blob/314f05b6a226e666a8ae4417b151d896606e7db4/algotom/prep/calculation.py#L296) will use these values:
    if start is None:
        start = ncol // 2 - ncol // 16
    if stop is None:
        stop = ncol // 2 + ncol // 16
If the sinogram width is small, the search range can be small.

In [Tomopy](https://tomopy.readthedocs.io/en/latest/api/tomopy.recon.rotation.html#tomopy.recon.rotation.find_center_vo), the search range is from -50 to +50 around the middle ( ncol // 2 - 50, ncol // 2 +50). This fixed range, however, can be a problem if the width of a sinogram smaller than 100.

You just need to change the search range of the function in Algotom to the same range as in Tomopy:
ncol = sinogram.shape[1]
find_center_vo(sino_180, start=ncol//2-50, stop=ncol//2+50)

**Comment by gbzan** [comment]
Thank you so much. It fixed by problem. Now the results are same now. Thank you again. It help me a lot.
![image](https://user-images.githubusercontent.com/32512895/166550952-cdcca75e-3489-4460-b887-b13928f53bba.png)

**Comment by gbzan** [comment]
I have one more question, Does this mothod work well on Cone-beam  tomography data?

**Comment by decarlof** [comment]
we set a default range as  smin=-50, smax=50 because in our data we try to do an alignment within that range. You can make it larger, in fact in [tomopy-cli ](https://github.com/tomography/tomopy-cli) you can pass these as parameters as     --center-search-width --rotation-axis.

I agree find_center_vo() is the most reliable we have. Thanks to @nghia-vo for writing it!

**Comment by nghia-vo** [comment]
@gban: it doesn't work for cone-beam. The community needs one which is reliable enough :)

**Comment by gbzan** [comment]
@nghia-vo Thank you. I tested two method (find_center_vo() and find_center())  in tomopy for a few datasets, find_center_vo() always gives me the reliable results.

**Comment by nghia-vo** [comment]
I mean a similar method for cone-beam.

**Comment by algotom** [comment]
I've added an improvement to warn users if the global minimum is out of the searching range. 
https://github.com/algotom/algotom/blob/91abf3af96d644608495e2d0ebe0976e34fe19d5/algotom/prep/calculation.py#L181

**Comment by gbzan** [comment]
Thannks for your great efforts.
