### ISSUE TITLE
How to understand the average process of the flat image and dark image?

### ISSUE THREAD

**Issue by gbzan** [algotom/algotom#8]
Hello Nghia,
      I read a part of the codes which are used for averaging the flat image and dark images.  Normally, we should average all the collected flat or dark images to one image.  But this part of codes seems not right. Please double check. Thank you.

# Code comes from:
https://algotom.github.io/toc/section1/section1_2.html

# Load flat images, average them.
flat_path = losa.find_file(flat_path + "/*.tif*")
flat = losa.load_image(flat_path[0])
for i in range(1, len(flat_path)):
    flat = (flat + losa.load_image(flat_path[i])) * 0.5

# Load dark images, average them.
dark_path = losa.find_file(dark_path + "/*.tif*")
dark = losa.load_image(dark_path[0])
for i in range(1, len(dark_path)):
    dark = (dark + losa.load_image(dark_path[i])) * 0.5

**Comment by nghia-vo** [comment]
Hello gbzan,
    If the images are not the same, two approaches are not the same. However, in practice flat-field images are the same. We add them up to reduce random noise (which has the same std and mean value in each image). To be clear:
     (a1 + a2 + a3)/3 != ((a1+a2) * 0.5 + a3) * 0.5
     (a + a + a)/3 = ((a+a) * 0.5 + a) * 0.5 = a
Another reason I used these codes because I don't have to figure out the shape and size of the data. 

In the latest version of Algotom (1.1.0), averaging a stack of tiff image can be done by a single [method](https://algotom.readthedocs.io/en/latest/api/algotom.io.loadersaver.html#algotom.io.loadersaver.get_image_stack):
Example:
```python
flat_field = algotom.io.loadersaver.get_image_stack(None, flat_path, average=True, crop=(0, 0, 0, 0), fix_zero_div=True)
```
Or we can load all images and averaging them using a Numpy method
```python
flats = algotom.io.loadersaver.get_tif_stack(flat_path, idx=None, crop=(0, 0, 0, 0), fix_zero_div=True)
flat_field = np.mean(flats, axis=0)
````

**Comment by nghia-vo** [comment]
I agree that the codes on the demonstration page are a bit confuse. I'll update that.

**Comment by gbzan** [comment]
Hi Nghia,
     Thanks for clarifying it. Normally, I load all images and averaging them using a Numpy method. 
     I unsderstand these formulas,
     (a1 + a2 + a3)/3 != ((a1+a2) * 0.5 + a3) * 0.5
    (a + a + a)/3 = ((a+a) * 0.5 + a) * 0.5 = a
     I agree that the flat images have the same std and mean value in each image. However, in practice flat-field images may not the same with the random noise.  I'd like to use the way that load all images and averaging them using a Numpy method. 
     Anyway, thanks for your great effort for making these loading functions.

**Comment by algotom** [comment]
The page has been updated https://algotom.github.io/toc/section1/section1_2.html#tiff-format

**Comment by gbzan** [comment]
Thank you update it. Before I wrote a part of codes to read all the tif files from a folder and apppend them as a stack without knowing the image sizes.
FYI,

import glob
import os
import tifffile
import numpy as np

def read_tif_from_folder(file_folder):
    print('Reading tif from a folder ...')
    image_stack = np.array([tifffile.imread(fn) for fn in glob.glob(os.path.join(file_folder, "*.tif"))])
    print('    Read image:', image_stack.shape)
    return image_stack

flat = np.mean(flat_stack, axis=0)
